# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Scrape Kings League Infojobs Website

on:
  workflow_dispatch:
  
  reporsitory_dispatch:
    types:
      - webhook
      
  schedule:
    - cron: "0 */1 * * 0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: borales/actions-yarn@v4
        with:
          cmd: install
      - run: |
        node scraping/leaderboard.js
        git config user.name kings-league-bot
        git add -A
        git commit -m "[bot] Update Kings League Databses"
        git push origin main
